goldmark:
    renderer:
        unsafe: true
tableOfContents:
    startLevel: 1
    endLevel: 2
    ordered: false
highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    tabWidth: 4
