mainSections:
  - post
featuredImageField: image
rssFullContent: true
favicon:

sidebar:
    emoji: "🖋️"
    subtitle:  "Works, books, and thoughts"
    avatar: "/avatar_202608.png"

footer:
    since: 2019
    customText: 

dateFormat:
    published: 2006-01-02
    lastUpdated: 2006-01-02 15:04 UTC

article:
    math: false
    toc: true
    readingTime: true
    license:
        enabled:

comments:
    enabled: true
    provider: giscus
    giscus:
        repo: 1nterp/1nterp.github.io
        repoID: MDEwOlJlcG9zaXRvcnkyMzY5NzQ5Mzc=
        category: General
        categoryID: MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyMjU4Mjgx
        mapping: pathname
        reactionsEnabled: 1
        emitMetadata: 1
        lang: en

widgets:
    homepage:
        - type: search
        - type: archives
          params:
              limit: 5
        - type: categories
          params:
              limit: 10
        - type: tag-cloud
          params:
              limit: 10
    page:
        - type: search
        - type: toc

opengraph:
    twitter:
        site: interp_
        card: summary_large_image

defaultImage:
    opengraph:
        enabled: false
        local: false
        src:

colorScheme:
    toggle: true
    default: auto

imageProcessing:
    cover:
        enabled: true
    content:
        enabled: true
