baseURL = "https://interp.blog/"
languageCode = "ko-kr"
title = "InterP Blog"
theme = "tale-hugo"
defaultContentLanguage = "ko"

[Author]
    name = "InterP"

sectionPagesMenu = "main"

# [Params]
#     css = ["override.css"]

pygmentsCodefences = true
pygmentsStyle = "monokai"
