baseurl: https://interp.blog/
languageCode: ko-kr
theme: stack
paginate: 6
title: InterP Blog

enableRobotsTXT: true

languages:
    ko:
        languageName: 한국어
        title: InterP Blog
        weight: 1
    en:
        languageName: English
        title: InterP Blog
        weight: 2

# Change it to your Disqus shortname before using
# disqusShortname: hugo-theme-stack

# GA Tracking ID
# googleAnalytics: UA-126809878-1

# Google Analytics 4
googleAnalyticsID: "G-KMRJ33V06X"

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: ko

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /:slug/
    page: /:slug/

params:
    mainSections:
      - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2019
        customText:

    dateFormat:
        published: 2006-01-02
        lastUpdated: 2006-01-02 15:04 UTC

    sidebar:
        subtitle: Things I'm interested
        # emoji: ":baseball:"
        avatar:
            enabled: false
            local: false
            src: /apple-touch-icon.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: 

    comments:
        enabled: false
        # provider: disqus

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: search
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site: interp_

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: 
        - identifier: home
          name: Home
          weight: -90
          url: /
          params:
              icon: home

    social:
        - identifier: linkedin
          name: LinkedIn
          url: https://linkedin.com/in/interp
          params:
              icon: brand-linkedin

        - identifier: github
          name: GitHub
          url: https://github.com/1nterp
          params:
              icon: brand-github

    #     - identifier: facebook
    #       name: Facebook
    #       url: https://www.facebook.com/1nterp
    #       params:
    #           icon: brand-facebook

    #     - identifier: instagram
    #       name: Instagram
    #       url: https://www.instagram.com/interp/
    #       params:
    #           icon: brand-instagram

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        startLevel: 1
        endLevel: 2
        ordered: false
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: false
        tabWidth: 4

enableEmoji: true