baseURL: https://interp.blog/
defaultContentLanguage: ko
languageCode: ko-kr
title: "InterP Blog"
theme: paper-mod
# theme: tale
sectionPagesMenu: main
googleAnalytics: UA-126809878-1
# disqusShortname: interp-blog

metaDataFormat: "yaml" # for forestry.io

params:
  comments: true
  defaultTheme: light
  ShowPostNavLinks: true
  # homeInfoParams:
  #   Title: InterP Blog
  profileMode:
    enabled: true
    title: "InterP" # optional default will be site title
    subtitle: "Cloud-service DevOps / Database-engine Developer"
    imageUrl: "avatar.jpg" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    # buttons:
    #   - name: Archive
    #     url: "/archives"
    #   - name: Github
    #     url: "https://github.com/1nterp"
    # Content: "The longer I am here, the smarter they will be"
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  author: ["InterP"]
  cover:
    relative: true
  mainSections:
  - tech
  - essay
  - review 
  socialIcons: # optional
  - name: "Github"
    url: "https://github.com/1nterp/"
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/interp/"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
  # - identifier: archive ### need to unite all date string, see '인간실격'
  #   name: Archives
  #   #pre: <i class='fa fa-heart'></i>
  #   url: /archives/
  #   weight: 100
  # - identifier: search ### need to configure fuse.js to hide drafts
  #   name: Search
  #   #pre: <i class='fa fa-heart'></i>
  #   url: /search/
  #   weight: 150
  - identifier: tech
    name: Tech
    #pre: <i class='fa fa-heart'></i>
    url: /tech/
    weight: -15
  - identifier: essay
    name: Essay
    #pre: <i class='fa fa-heart'></i>
    url: /essay/
    weight: -10
  - identifier: review
    name: Review
    #pre: <i class='fa fa-heart'></i>
    url: /review/
    weight: -10

pygmentsCodefences: true
pygmentsStyle: monokai

markup:
  goldmark:
    renderer:
      unsafe: true